### ISSUE TITLE
Test invocation

### ISSUE THREAD

**Issue by wwadge** [thomasdarimont/spring-boot-keycloak-server-example#1]
Hi,

Do you have any hints on how you can invoke endpoints on the embedded keycloak server? I've tried /auth/token and so on but everything seems to be returning a 404.

I would eventually like to invoke it via a mockmvc instance so I can document requests/responses via Spring Rest Docs.

**Comment by thomasdarimont** [comment]
This project moved over to a new place: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server
