### ISSUE TITLE
can not run on desktop

### ISSUE THREAD

**Issue by david0718** [thomasdarimont/spring-boot-keycloak-server-example#15]
Hey 
after build and run the command to start the app.
It pops below error at the end.
Any idea?

Thanks 
David
_______________________________________________________________________________________________________
2020-02-16 11:20:36.925 ERROR 10544 --- [           main] liquibase.changelog.ChangeSet            : Change Set META-INF/jpa-changelog-8.0.0.xml::8.0.0-credential-clean
up::keycloak failed.  Error: Table "FED_CREDENTIAL_ATTRIBUTE " not found; SQL statement:
DROP TABLE PUBLIC."FED_CREDENTIAL_ATTRIBUTE " [42102-200] [Failed SQL: (42102) DROP TABLE PUBLIC."FED_CREDENTIAL_ATTRIBUTE "]

**Comment by david0718** [comment]
Hi， I found this is a bug for 8.0.2 tagged version for the jpa changelog file as below.
the value for the tableName contains space.
That is it.

Thanks, just for information.

David
____________________________________________________________________________________________
 
        <dropTable tableName="FED_CREDENTIAL_ATTRIBUTE "/>

**Comment by thomasdarimont** [comment]
This project moved over to a new place: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server
