### ISSUE TITLE
column "counter" not found;

### ISSUE THREAD

**Issue by dvsingh9** [thomasdarimont/spring-boot-keycloak-server-example#16]
`2020-03-06 12:44:24.224 ERROR 20201 --- [  restartedMain] liquibase.changelog.ChangeSet            : Change Set META-INF/jpa-changelog-8.0.0.xml::8.0.0-credential-cleanup::keycloak failed.  Error: Column "COUNTER" not found; SQL statement:
ALTER TABLE PUBLIC.CREDENTIAL ALTER COLUMN  COUNTER SET DEFAULT NULL [42122-200] [Failed SQL: (42122) ALTER TABLE PUBLIC.CREDENTIAL ALTER COLUMN  COUNTER SET DEFAULT NULL]`

**Comment by cfpperche** [comment]
@dvsingh9  Hi, Did you solve ?

**Comment by thomasdarimont** [comment]
This project moved over to a new place: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server
