### ISSUE TITLE
Invalid token issuer when running keycloak behind proxy

### ISSUE THREAD

**Issue by frdiansyah11** [thomasdarimont/spring-boot-keycloak-server-example#17]
I try to run a keycloak from a proxy, when I try to authenticate a token, I get a message like this:

WWW-Authenticate: Bearer realm="sample", error="invalid_token", error_description="Invalid token issuer. Expected 'http://keycloak:8080/auth/realms/sample', but was 'http://keycloak/auth/realms/sample'"	

how to solve it ? or like in the docker I have to set like PROXY_ADDRESS_FORWARDING=true

**Comment by thomasdarimont** [comment]
Take a look at: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-use-behind-a-proxy-server

This project moved over to: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server
