### ISSUE TITLE
Using PostgreSQL easily possible with this Spring Boot setup?

### ISSUE THREAD

**Issue by berndgoetz** [thomasdarimont/spring-boot-keycloak-server-example#6]
Hi Thomas, All,
this is a great way to play around with Keycloak, many thanks for it! Now, I'd like to run it using a database, such as PostgreSQL. Can that be easily configured? If yes, how and where could that be done?
Many thanks in advance.
Best regards,
Bernd

**Comment by thomasdarimont** [comment]
@berndgoetz take a look at the example in https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server there you can setup the datasource as you are used to in spring boot apps.

This project moved over to a new place: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server
