### ISSUE TITLE
org.apache.tomcat.jdbc.pool.PoolExhaustedException

### ISSUE THREAD

**Issue by giraone** [thomasdarimont/spring-boot-keycloak-server-example#7]
When working with the admin console after startup, sooner or later the application hangs because the JDBC connections are exhausted. I have increased spring.datasource.max-active, but this only postpones the error.
 
`org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-9] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:50; busy:50; idle:0; lastwait:30000].`

**Comment by thomasdarimont** [comment]
This has been fixed in the meantime.

This project moved over to a new place: https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server
